#!/bin/sh
for i in `sed -e 's/ //g' $1`
do
	echo $i
	./proveformula "$i"
	if [ $? != 0 ]
	then
		echo "$?"
		echo "Failure: could not prove above assertion.  Stopping early."
		exit
	fi
	echo
done
echo "Success: proved all problems in $1."
